#!/usr/bin/env python3
"""Merge priority sources into one S5 round-2 triage TSV.

Each input is either:
  - gene_id\\treason   (two+ columns; extra columns ignored), or
  - output of 02_priority_loci.py (gene_id, psauron, family, reason), or
  - a bare list of gene IDs (one per line).

Reasons from multiple files are joined with '|'.

Example:
  python3 pipeline/02b_merge_priority_r2.py \\
    -o "$WORK_DIR/priority_rounds/priority_r2.tsv" \\
    --from-priority "$WORK_DIR/priority_rounds/priority_r1.tsv" \\
    --from-priority "$WORK_DIR/priority_rounds/priority_r2_psauron.tsv" \\
    --from-ids-reason "$WORK_DIR/priority_rounds/busco_fragmented.tsv" \\
    --from-ids-reason "$WORK_DIR/priority_rounds/omark_flags.tsv" \\
    --log "$WORK_DIR/priority_rounds/priority_r2_build.md"
"""
from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path


def _label(path: Path, default_reason: str) -> str:
    if default_reason:
        return default_reason
    # Prefer filename stem; avoid raw /dev/fd/N from process substitution
    name = path.name
    if name.isdigit() or path.as_posix().startswith("/dev/fd/"):
        return "input"
    return path.stem


def load_rows(path: Path, default_reason: str) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    text = path.read_text(encoding="utf-8", errors="replace")
    fallback = _label(path, default_reason)
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        # skip header-ish
        if parts[0].lower() in {"gene_id", "gene", "id"}:
            continue
        gid = parts[0].strip()
        if not gid:
            continue
        if len(parts) == 1:
            reason = fallback
        elif len(parts) >= 4 and parts[3].strip():
            # 02_priority_loci.py style
            reason = parts[3].strip()
        elif len(parts) >= 2 and parts[1].strip():
            reason = parts[1].strip()
        else:
            reason = fallback
        out.append((gid, reason))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--out", type=Path, required=True)
    ap.add_argument(
        "--from-priority",
        type=Path,
        action="append",
        default=[],
        help="02_priority_loci.py TSV or gene_id\\treason (repeatable)",
    )
    ap.add_argument(
        "--from-ids-reason",
        type=Path,
        action="append",
        default=[],
        help="gene_id\\treason TSV or bare gene_id list (repeatable)",
    )
    ap.add_argument(
        "--default-reason",
        default="",
        help="fallback reason label when an input line has no reason column",
    )
    ap.add_argument("--log", type=Path, help="optional markdown build log")
    args = ap.parse_args()

    merged: dict[str, list[str]] = defaultdict(list)
    sources: list[tuple[str, int]] = []

    for label, paths in (
        ("priority", args.from_priority),
        ("ids_reason", args.from_ids_reason),
    ):
        for path in paths:
            if not path.exists():
                raise SystemExit(f"missing input: {path}")
            rows = load_rows(path, args.default_reason or path.name)
            sources.append((f"{label}:{path}", len(rows)))
            for gid, reason in rows:
                if reason not in merged[gid]:
                    merged[gid].append(reason)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as fh:
        fh.write("gene_id\treasons\tn_sources\n")
        for gid in sorted(merged.keys()):
            reasons = merged[gid]
            fh.write(f"{gid}\t{'|'.join(reasons)}\t{len(reasons)}\n")

    print(f"wrote {len(merged)} loci -> {args.out}")

    if args.log:
        lines = [
            "# priority_r2 build log",
            "",
            f"Output: `{args.out}` ({len(merged)} gene_ids)",
            "",
            "## Inputs",
            "",
        ]
        for src, n in sources:
            lines.append(f"- `{src}` — {n} rows read")
        lines += ["", f"Generated by `pipeline/02b_merge_priority_r2.py`.", ""]
        args.log.parent.mkdir(parents=True, exist_ok=True)
        args.log.write_text("\n".join(lines), encoding="utf-8")
        print(f"wrote log -> {args.log}")


if __name__ == "__main__":
    main()
